---
title: "Working Through H. Wickham’s ggpllot2"
author: 'Krista DeStasio'
date: "4/25/2017"
output: html_document
---

```{r}
# Clear the workspace
rm(list=ls())

# Install and load required packages
list.of.packages <- c("ggplot2")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])] 
if(length(new.packages)) install.packages(new.packages) 
library(ggplot2)
```
## qplot()
```{r 2.2 Datasets}
set.seed(1410) # Make the sample reproducible
dsmall <- diamonds[sample(nrow(diamonds), 100),]
```
```{r 2.3 Basic Use}
# Scatterplot showing relationship between price and carats
qplot(carat, price, data=diamonds)

# Transform the variables since the relationship looks exponential
qplot(log(carat), log(price), data=diamonds)

# Look at relationship between volume (x*y*z) and weight
qplot(carat, x*y*z, data=diamonds)
```
```{r 2.4 Aesthetic Attributes}
# Augment the plot of carat and price with informa- tion about diamond colour and cut
qplot(carat, price, data=dsmall, color=color)
qplot(carat, price, data=dsmall, shape=cut)

# Manually set aesthetics with I(), use the alpha aesthetic to make a semi-transparent color
qplot(carat, price, data=diamonds, alpha=I(1/10))
qplot(carat, price, data=diamonds, alpha=I(1/100))
qplot(carot, price, data=diamonds, alpha=I(1/200))
```
### 2.5 Plot geoms  
#### 2-dimensional distributions  
geom = "point"  
geom = "smooth"  
geom = "boxplot"  
geom = "path" _or_ geom = "line"  

#### 1-dimensional distributions  
geom = "histogram"  
geom = "freqpoly"
geom = "density"  
geom = "bar"  
```{r 2.5.1 Adding a smoother to a plot}
qplot(carat, price, data=dsmall, geom=c("point", "smooth"))
qplot(carat, price, data=diamonds, geom = c("point", "smooth"))

# controlling the "wiggliness" of the line
qplot(carat, price, data = dsmall, geom = c("point", "smooth"), span=0.2)
qplot(carat, price, data = dsmall, geom = c("point", "smooth"), span=1)

# Using lm
library(splines)
qplot(carat, price, data=dsmall, geom=c("point", "smooth"), method="lm")
qplot(carat, price, data=dsmall, geom=c("point","smooth"), method="lm", formula= y ~ ns(x,5))

# For a more robust fit that is less affected by outliers
library(MASS)
qplot(carat, price, data=dsmall, geom=c("point", "smooth"), method="rlm")
```
```{r 2.5.2 Boxplots and jittered points}

```

```